# Generated by Django 4.2.5 on 2023-09-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="dishes",
            field=models.ManyToManyField(related_name="menus", to="restaurant.dish"),
        ),
    ]
